### ISSUE TITLE
Google Drive link broken

### ISSUE THREAD

**Issue by jyluo** [typetools/checker-framework-inference#18]
The google drive link in https://github.com/typetools/checker-framework-inference/blob/master/README for the additional documents requires special permissions to access, and is inaccessible from a public computer with or without logging into any google account.

**Comment by mernst** [comment]
Thanks for pointing that out.  I changed the text to indicate that the information is for developers and is being moved into the repository where it belongs.  We have already done that with some information and should continue to do so.  Other documents there are temporary (such as about a refactoring in progress) or obsolete.
