### ISSUE TITLE
Check for plume.jar

### ISSUE THREAD

**Issue by mernst** [typetools/checker-framework-inference#3]
checker-framework-inference/dist does not contain plume.jar, which checker-framework-inference/scripts/inference assumes it contains.
Furthermore, "gradle dist" does not fail if plume.jar is not found.

This works around the problem:
  cd $JSR308
  ln -s $pl .
  cd $cfi
  gradle dist

But "gradle dist" should fail if plume.jar is not found rather than continuing without error.

**Comment by smillst** [comment]
The inference framework now uses the plume.jar in AFU.

(Fixed by fb05daeb2885a9c5)
